### ISSUE TITLE
The item Is not working. 

### ISSUE THREAD

**Issue by allyaminou** [NNakreSS/nakres_barbecue#1]
Hi, so i'm using esx with ox_inv.   
when I try to use the item ''bbq'' it spawns the props. But when I try to remove the bbq it doens't go away. 
I'm on esx with ox_inventoryu / ox_target. 

also I get insuficient error that i don't have the items for cooking, but i have them in my inventory, 

And this is what i get 

https://prnt.sc/R22IrfPPoZlN

**Comment by NNakreSS** [comment]
If you made any additions to 'foods.lua', could you please share the entire code?
